// Callow Downs, box E3: Crowness. Core, band 3-4: the Salt Road west along the coast from Gullwick to
// the corner of D3, the gibbet above the rocks, and Crowness Light on the point, with the keeper's
// cottage under it and the rocks below, where the wreckers show their own light. The stubble in the
// north-east corner, across the Wend from Gullwick, is left for Ashcombe (#87). Cut from the atlas by
// tools/scaffold.ts; docs/areas/shelf.md §4.4 is its brief.
import type { MapDef } from '../../../../game/map.ts';
import { WEST } from '../../../../game/types.ts';

export const DOWNS_E3: MapDef = {
  id: 'downs_e3',
  name: 'Callow Downs',
  kind: 'outdoor',
  density: 'core',
  band: [3, 4],
  start: { x: 31, y: 10, facing: WEST },
  rows: [
    ',,,,,,,,,,,fffffffffffffffff~fff',
    ',,,,,,,,,,,fffffffffffffffff~~ff',
    ',,,TT,,,,,,,,fffffffffffffffff=f',
    ',,TTTT,,,,,,,,ffffffffffffffff~~',
    ',,,TT,,,,,,,,,^,fffffffffffffff~',
    ',,,,,,,,,,,,^^,,,fffffffffffffff',
    ',,,,,,,,,,,^^^,,,,,fffffffffffff',
    ',,,,,,,,,,,^^^,,,,,,,,,,ffffffff',
    ',,,,,,,,,,,,,,,,,,,,,,,,,fffffff',
    ',,,,,,,,,,,,,,,,,,,,,,,,,,,,ffff',
    ',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,=',
    ',,,,,,,,,,,,,,,,,,,,,,,,,,,,,===',
    ',,,,,,,,,,,,,,,,,,,,,,,,,,,,==,r',
    ',,,,,,,,,,,,,,,,,,,,,,,,,,==,,rr',
    ',,,,,,,,,,,,,,,,,,,,,,,,===,,,rr',
    ',,,,,,,,,,,,,,,,,,,,,,,==,,,,,,r',
    ',,,,,,,,,,,,,,,,,,,,,,==,,,,,,,,',
    ',,,,,,,,,,,,,,,,,,,,==,,,,,,,,,_',
    ',,,,,,,,,,,,,,,,,,==,,,,,,,,,,_~',
    ',,,,,,,,,,,,,,,,,==,,,,,,,,,__~~',
    ',,,,,,,,,,,,,,,===,,,,,_^^,_~~~W',
    ',,,,,,,,,,,,,,==,,,,,,_~~~r~~~WW',
    ',,,,,,,,,,,,==,,,,,,__~~~~~~WWWW',
    ',,,,,,,,,,,==:,,,,,_~~~WWW~WWWWW',
    ',,,,,,,,,==,,::,,,,_~~WWWWWWWWWW',
    ',,,,,,,===,,,,::,^^_~WWWWWWWWWWW',
    ',,^^^,==,,,,,,,:::^^_~WWWWWWWWWW',
    ',^^^===,,,,,,_,^B:,,^_~WWWWWWWWW',
    ',^^==^,,,,,,_~~r,:::B,r~WWWWWWWW',
    ',==^^^^,,,,,_~~~rr_S__r~WWWWWWWW',
    '==^^^^^^,,,__~~WW~r_r_r~WWWWWWWW',
    ',,,,^^^^,__~~~WWWWWWWWWWWWWWWWWW',
  ],
  features: [
    { kind: 'event', x: 30, y: 2, id: 'e3_ford', once: true, text: 'The Wend\'s last bend, and a ford of flat stones. Gullwick\'s smoke across the water.' },
    { kind: 'event', x: 20, y: 9, id: 'e3_point', once: true, text: 'Out on the point, a lighthouse. No light in it.' },
    { kind: 'event', x: 25, y: 15, id: 'e3_gibbet', once: true, text: 'A gibbet above the rocks. The man in it wore oilskins, and a board at his feet says WRECKER.' },
    { kind: 'sign', x: 14, y: 22, text: 'A finger-post where a path leaves the road: CROWNESS LIGHT.' },
    { kind: 'shrine', x: 12, y: 24, id: 'e3_shrine', text: 'A shrine where the path leaves the road, hung with a fisherman\'s lantern. Its glass is cracked.', stat: 'luck', done: 'The shrine is quiet.' },
    { kind: 'cairn', x: 19, y: 26, id: 'e3_cairn', text: 'A cairn on the point, a stone for every boat Crowness lost.', gold: 30, items: ['potion_heal'] },
    { kind: 'camp', x: 12, y: 27, name: 'The lee of the point', text: 'Out of the wind in the lee of the point, on old ashes.' },
    { kind: 'well', x: 18, y: 27, text: 'The keeper\'s well. A bucket, and a rope worn to a thread.' },
    { kind: 'event', x: 21, y: 29, id: 'e3_wreck', once: true, text: 'A wreck on the rocks below the light, her back broken. Someone has had the cargo, but not all of it.' },
    { kind: 'chest', x: 21, y: 30, id: 'e3_salvage', gold: 50, items: ['buckler+1', 'potion_heal'] },
    { kind: 'event', x: 18, y: 29, id: 'e3_ledge', once: true, text: 'A ledge low on the rocks, black with lamp soot. No keeper set a lamp this low.' },
    { kind: 'event', x: 19, y: 29, id: 'e3_niche', once: true, text: 'A niche in the rock: a shuttered lamp, and a chart of the reef with the rocks marked as a harbour.' },
    { kind: 'chest', x: 19, y: 30, id: 'e3_niche_chest', gold: 40, items: ['potion_sp'] },
    { kind: 'event', x: 5, y: 9, id: 'e3_pond', once: true, text: 'A dew pond on the down, its rim trodden by sheep and by something heavier.' },
    { kind: 'event', x: 5, y: 17, id: 'e3_fold', once: true, text: 'A shepherd\'s fold of piled flints, the gate off its hinge and no sheep.' },
  ],
  secrets: [{ x: 19, y: 29, hint: 'e3_ledge' }],
  encounters: [
    { id: 'e3_crows', x: 27, y: 16, monsters: ['carrion_crow', 'carrion_crow', 'carrion_crow', 'carrion_crow', 'carrion_crow', 'carrion_crow', 'carrion_crow', 'carrion_crow'], aware: 5, respawn: 1440 },
    { id: 'e3_fog', x: 18, y: 18, when: { sky: 'fog' }, monsters: ['lampman', 'wrecker', 'wrecker', 'wrecker', 'wrecker'], aware: 3, respawn: 2880 },
    { id: 'e3_rocks', x: 25, y: 20, when: { hours: 'night' }, monsters: ['wrecker', 'wrecker', 'lampman'], aware: 5, respawn: 2880 },
    { id: 'e3_bay', x: 12, y: 29, when: { hours: 'night' }, monsters: ['wrecker', 'wrecker', 'lampman'], aware: 5, respawn: 2880 },
    { id: 'e3_crabs', x: 21, y: 28, monsters: ['barnacle_crab', 'barnacle_crab', 'barnacle_crab', 'barnacle_crab'], aware: 3, respawn: 1440 },
    { id: 'e3_bandits', x: 5, y: 27, monsters: ['billman', 'billman', 'slinger'], aware: 5, respawn: 2880 },
    { id: 'e3_wolves', x: 12, y: 5, monsters: ['chalk_wolf', 'chalk_wolf', 'chalk_wolf'], aware: 5, respawn: 1440 },
    { id: 'e3_tusker', x: 2, y: 5, monsters: ['tusker'], aware: 3, respawn: 2880 },
  ],
};
