// The Foreland: the starting coast. Helmstow at the north, the Ashcombe farm to the south-east,
// woods to the west, marsh and the sea at the south, the caves at Brandy Hole in the south-west
// cliffs, and the pass east to Thornmark, open, where a Warden checkpoint warns every company that
// goes through. Difficulty band 1-5.
import type { MapDef } from '../../../../game/map.ts';
import { EAST, NORTH, SOUTH, WEST } from '../../../../game/types.ts';

export const SHELF: MapDef = {
  id: 'shelf',
  name: 'The Foreland',
  kind: 'outdoor',
  density: 'core',
  band: [1, 5],
  start: { x: 16, y: 4, facing: NORTH },
  rows: [
    'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM',
    'M,,,,,,,,,,,,,BBBBB,,,,,,,,,,,,M',
    'M,,T,,,,,,,,,,BBBBB,,,,,T,,,,,,M',
    'M,,,,,T,,,,,,,BB=BB,,,,,,,,T,,,M',
    'M,,,,,,,,,,,,,,,=,,,,,,,,,,,,,,M',
    'M,,,,TT,,,,,,,,,=,,,,,,TT,,,,,,M',
    'M,,,TTT,,,,,,,,,=,,,,,TTTT,,,,,M',
    'M,,,,T,,,,,,,,,,=,,,,,,TT,,,,,,M',
    'M,,,,,,,,,,,,,,,=,,,,,,,,,,,,,,M',
    'M,,,,,,,,,,,,===================',
    'M,,,,,,,,,,,,=,,,,,,,,,,,,r,,,,M',
    'M,,,,,,,,,,,,=,,,,,,,,,,,rr,,,,M',
    'M,,,TT,,,,,,,=,,,,,,,,,,,,r,,,,M',
    'M,,TTTT,,,,,,=,,,,,,,,,,,,,,,,,M',
    'M,,TTTT,,,,,,=,,,,,,,,,,,,,,,,,M',
    'M,,,TT,,,,,,,=,,,,,,,,,,,,,,,,,M',
    'M,,,,,,,,,,,,======,,,,,,,,,,,,M',
    'M,,,,,,,,,,,,,,,,,=,,,,,,,,,,,,M',
    'M,,,,,,,,,,,,,,,,,=,,,,,,,,,,,,M',
    'M,,,,,,,,,,,,,,,,,=,,,,,,BBBB,,M',
    'M,,,,,,,,,,,,,,,,,======DBBB,,,M',
    'M,,,,,,,,,,,,,,,,,,,,,,,,BBBB,,M',
    'M,,,,,,ww,,,,,,,,,,,,,,,,::::,,M',
    'M,,,,,wwww,,,,,,,,,,,,,,,,,,,,,M',
    'M,,,,,www,,,,,,,,,,,,,,,,,,,,,,M',
    'M,,,,,,w,,,,,,,,,,,,,,,,,,,,,,,M',
    'M,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,M',
    'MMMM,,,,,,,,,,,,,,,,,,,,,,,,,,,M',
    'M______________________________M',
    '=________~~~~~~~~~~~~~~~~~~~~~~M',
    'M________WWWWWWWWWWWWWWWWWWWWWWM',
    'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM',
  ],
  exits: [
    { x: 16, y: 3, to: 'harrow', tx: 7, ty: 14, tf: NORTH, label: 'You enter Helmstow.' },
    { x: 24, y: 20, to: 'mill', tx: 1, ty: 1, tf: EAST, label: 'The farmhouse door hangs open. Stairs lead down into the cellar.' },
    { x: 31, y: 9, to: 'thornmark', tx: 1, ty: 9, tf: EAST, label: 'The pass opens onto old forest. Thornmark.' },
    { x: 2, y: 28, to: 'greywater1', tx: 1, ty: 1, tf: SOUTH, label: 'A cave mouth in the cliff foot, half hidden by kelp. Brandy Hole.' },
    { x: 0, y: 29, to: 'downs_f2', tx: 30, ty: 29, tf: WEST, label: 'The Salt Road climbs off the beach onto the Downs.' },
  ],
  features: [
    { kind: 'sign', x: 16, y: 4, text: 'North: Helmstow. South and east along the road: Ashcombe farm.' },
    { kind: 'sign', x: 13, y: 9, text: 'South: the coast and Ashcombe. West along the beach: Brandy Hole. East: the pass to Thornmark, Warden road.' },
    { kind: 'sign', x: 30, y: 9, text: 'Warden checkpoint. The road east is open. Past it lies Thornmark, and the Wardens will not come in after you.' },
    { kind: 'sign', x: 18, y: 16, text: 'East: Ashcombe.' },
    { kind: 'event', x: 23, y: 20, id: 'ashcombe_gate', once: true, text: 'Ashcombe. The gate is off its hinges and the yard is silent. Something has scraped the earth in a wide ring around the house.' },
    { kind: 'event', x: 15, y: 28, id: 'coast', once: true, text: 'The sea. Out on the water, far off, the column of the Hearth stands against the sky. It flickers.' },
    { kind: 'npc', x: 29, y: 8, name: 'Captain Hale, Warden of the Scarth', lines: [
      'A grizzled Warden with a bandaged arm sits on a crate by the checkpoint, and gets up when he sees you, which costs him something.',
      '"Smugglers. They\'ve holed up in Brandy Hole, the caves at the west end of the beach. I lost three men going in after them, and the one who came back talks about worse than smugglers. I believe him. I\'ve an arm that believes him."',
      '"Clear them out and bring me their ledger. I want the names of everyone in Helmstow who has been buying from them. Not the brandy; the names."',
      '"The pass is open. I\'ll not shut a road because I can\'t hold a cave. But it\'s mine to warn you about, and I\'m warning you: Thornmark\'s wolves are twice the size of ours."',
    ], flag: 'q_greywater', quest: {
      item: 'greywater_ledger', reward: 400, setFlag: 'q_greywater_done',
      early: [
        'A grizzled Warden with a bandaged arm gets up off a crate by the checkpoint. "That\'s the Brandy Hole ledger. I lost three men going in after it."',
        'He leafs through it, and his face goes grey. "Names, dates, and a column headed CARGO BELOW. People. The Ash, here, under our feet."',
        'He shuts the book. "Nobody sent you, and you went. You\'ve earned this. I\'ll see the Regent-Warden gets a copy."',
        '"The pass is open, and it\'s mine to warn you: Thornmark\'s wolves are twice the size of ours."',
      ],
      done: [
        'Hale leafs through the ledger, and his face goes grey by the page.',
        '"These aren\'t smugglers\' accounts. Names. Dates. A column headed CARGO BELOW." His finger stops halfway down it. "Wenna, of Gullwick. In a neat clerk\'s hand, like a cask of brandy."',
        'He shuts the book. "People. The Ash, here, under our feet, and I\'ve been sitting on a crate on top of it."',
        '"You\'ve earned this, and more than I\'ve got. The Regent-Warden gets a copy. It\'s the sort of thing a Regent wants."',
      ],
      after: ['"The pass is yours; it always was. Mind yourselves in Thornmark. The wolves are twice the size of ours and the trees are older than Helmstow, and the elves will thank you for neither observation."'],
    } },
    { kind: 'sign', x: 3, y: 28, text: 'Brandy Hole. Chalked beneath, in Warden hand: CLOSED. DO NOT ENTER. ASK CAPT. HALE.' },
    { kind: 'well', x: 26, y: 22, text: 'A cistern behind the farm. The water is clean.', heal: true },
  ],
  encounters: [
    { id: 'road_rats', x: 16, y: 7, monsters: ['rat', 'rat', 'rat'], aware: 4, respawn: 1440 },
    { id: 'wood_wolves', x: 5, y: 8, monsters: ['wolf', 'wolf'], aware: 5, respawn: 1440 },
    { id: 'wood_boar', x: 7, y: 13, monsters: ['boar'], aware: 3, respawn: 2880 },
    { id: 'road_bandits', x: 13, y: 12, monsters: ['bandit', 'bandit', 'bandit_archer'], aware: 5, respawn: 2880 },
    { id: 'hill_wolves', x: 24, y: 11, monsters: ['wolf', 'wolf', 'wolf'], aware: 5, respawn: 1440 },
    { id: 'marsh_spiders', x: 7, y: 23, monsters: ['spider', 'spider', 'spider', 'spider'], aware: 4, respawn: 1440 },
    { id: 'farm_rats', x: 22, y: 20, monsters: ['rat', 'rat', 'rat', 'rat', 'rat'], aware: 4, respawn: 720 },
    { id: 'beach_crabs', x: 9, y: 28, monsters: ['shore_crab', 'shore_crab', 'shore_crab', 'shore_crab'], aware: 4, respawn: 1440 },
    { id: 'cliff_smugglers', x: 5, y: 26, monsters: ['smuggler', 'smuggler', 'smuggler', 'smuggler_bowman'], aware: 5, respawn: 2880 },
    { id: 'coast_bandits', x: 20, y: 27, monsters: ['bandit', 'bandit', 'bandit', 'bandit_archer', 'bandit_archer'], aware: 5, respawn: 2880 },
  ],
};
