// The Foreland: the starting coast. Helmstow at the north, the Ashcombe farm to the south-east,
// woods to the west, marsh and the sea at the south, the caves at Brandy Hole in the south-west
// cliffs, and the pass east to Thornmark, open, where a Warden checkpoint warns every company that
// goes through. Difficulty band 1-5.
import type { MapDef } from '../../../../game/map.ts';
import { EAST, NORTH, SOUTH, WEST } from '../../../../game/types.ts';

export const SHELF: MapDef = {
  id: 'shelf',
  name: 'The Foreland',
  kind: 'outdoor',
  density: 'core',
  band: [1, 5],
  start: { x: 16, y: 4, facing: NORTH },
  rows: [
    'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM',
    'M,,,,,,,,,,,,,BBBBB,,,,,,,,,,,,M',
    'M,,T,,,,,,,,,,BBBBB,,,,,T,,,,,,M',
    'M,,,,,T,,,,,,,BB=BB,,,,,,,,T,,,M',
    'M,,,,,,,,,,,,,,,=,,,,,,,,,,,,,,M',
    'M,,,,TT,,,,,,,,,=,,,,,,TT,,,,,,M',
    'M,,,TTT,,,,,,,,,=,,,,,TTTT,,,,,M',
    'M,,,,T,,,,,,,,,,=,,,,,,TT,,,,,,M',
    'M,,,,,,,,,,,,,,,=,,,,,,,,,,,,,,M',
    'M,,,,,,,,,,,,===================',
    'M,,,,,,,,,,,,=,,,,,,,,,,,,r,,,,M',
    'M,,,,,,,,,,,,=,,,,,,,,,,,rr,,,,M',
    'M,,,TT,,,,,,,=,,,,,,,,,,,,r,,,,M',
    'M,,TTTT,,,,,,=,,,,,,,,,,,,,,,,,M',
    'M,,TTTT,,,,,,=,,,,,,,,,,,,,,,,,M',
    'M,,,TT,,,,,,,=,,,,,,,,,,,,,,,,,M',
    'M,,,,,,,,,,,,======,,,,,,,,,,,,M',
    'M,,,,,,,,,,,,,,,,,=,,,,,,,,,,,,M',
    'M,,,,,,,,,,,,,,,,,=,,,,,,,,,,,,M',
    'M,,,,,,,,,,,,,,,,,=,,,,,,BBBB,,M',
    'M,,,,,,,,,,,,,,,,,======DBBB,,,M',
    'M,,,,,,,,,,,,,,,,,,,,,,,,BBBB,,M',
    'M,,,,,,ww,,,,,,,,,,,,,,,,::::,,M',
    'M,,,,,wwww,,,,,,,,,,,,,,,,,,,,,M',
    'M,,,,,www,,,,,,,,,,,,,,,,,,,,,,M',
    'M,,,,,,w,,,,,,,,,,,,,,,,,,,,,,,M',
    'M,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,M',
    'MMMM,,,,,,,,,,,,,,,,,,,,,,,,,,,M',
    'M______________________________M',
    '=________~~~~~~~~~~~~~~~~~~~~~~M',
    'M________WWWWWWWWWWWWWWWWWWWWWWM',
    'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM',
  ],
  exits: [
    { x: 16, y: 3, to: 'harrow', tx: 7, ty: 14, tf: NORTH, label: 'You enter Helmstow.' },
    { x: 24, y: 20, to: 'mill', tx: 1, ty: 1, tf: EAST, label: 'The farmhouse door hangs open. Stairs lead down into the cellar.' },
    { x: 31, y: 9, to: 'thornmark', tx: 1, ty: 9, tf: EAST, label: 'The pass opens onto old forest. Thornmark.' },
    { x: 2, y: 28, to: 'greywater1', tx: 1, ty: 1, tf: SOUTH, label: 'A cave mouth in the cliff foot, half hidden by kelp. Brandy Hole.' },
    { x: 0, y: 29, to: 'downs_f2', tx: 30, ty: 29, tf: WEST, label: 'The Salt Road climbs off the beach onto the Downs.' },
  ],
  features: [
    { kind: 'sign', x: 16, y: 4, text: 'North: Helmstow. South and east along the road: Ashcombe farm.' },
    { kind: 'sign', x: 13, y: 9, text: 'South: the coast and Ashcombe. West along the beach: Brandy Hole. East: the pass to Thornmark, Warden road.' },
    { kind: 'sign', x: 30, y: 9, text: 'Warden checkpoint. The road east is open. Past it lies Thornmark, and the Wardens will not come in after you.' },
    { kind: 'sign', x: 18, y: 16, text: 'East: Ashcombe.' },
    { kind: 'event', x: 23, y: 20, id: 'ashcombe_gate', once: true, text: 'Ashcombe. The gate is off its hinges and the yard is silent. Something has scraped the earth in a wide ring around the house.' },
    { kind: 'event', x: 28, y: 9, id: 'scarth_watch', once: true, text: 'The Scarth. A pole across the road, a brazier and two Wardens with nothing to do but watch the pole.' },
    { kind: 'event', x: 15, y: 28, id: 'coast', once: true, text: 'The sea. Out on the water, far off, the column of the Hearth stands against the sky. It flickers.' },
    { kind: 'npc', x: 29, y: 8, name: 'Captain Hale, Warden of the Scarth', lines: [
      'A grizzled Warden with a bandaged arm sits on a crate by the checkpoint, and gets up when he sees you, which costs him something.',
      '"Smugglers. They\'ve holed up in Brandy Hole, the caves at the west end of the beach. I lost three men going in after them, and the one who came back talks about worse than smugglers. I believe him. I\'ve an arm that believes him."',
      '"Clear them out and bring me their ledger. I want the names of everyone in Helmstow who has been buying from them. Not the brandy; the names."',
      '"The pass is open. I\'ll not shut a road because I can\'t hold a cave. But it\'s mine to warn you about, and I\'m warning you: Thornmark\'s wolves are twice the size of ours."',
    ], flag: 'q_greywater', quest: {
      item: 'greywater_ledger', reward: 400, setFlag: 'q_greywater_done',
      early: [
        'A grizzled Warden with a bandaged arm gets up off a crate by the checkpoint. "That\'s the Brandy Hole ledger. I lost three men going in after it."',
        'He leafs through it, and his face goes grey. "Names, dates, and a column headed CARGO BELOW. People. The Ash, here, under our feet."',
        'He shuts the book. "Nobody sent you, and you went. You\'ve earned this. I\'ll see the Regent-Warden gets a copy."',
        '"The pass is open, and it\'s mine to warn you: Thornmark\'s wolves are twice the size of ours."',
      ],
      done: [
        'Hale leafs through the ledger, and his face goes grey by the page.',
        '"These aren\'t smugglers\' accounts. Names. Dates. A column headed CARGO BELOW." His finger stops halfway down it. "Wenna, of Gullwick. In a neat clerk\'s hand, like a cask of brandy."',
        'He shuts the book. "People. The Ash, here, under our feet, and I\'ve been sitting on a crate on top of it."',
        '"You\'ve earned this, and more than I\'ve got. The Regent-Warden gets a copy. It\'s the sort of thing a Regent wants."',
      ],
      after: ['"The pass is yours; it always was. Mind yourselves in Thornmark. The wolves are twice the size of ours and the trees are older than Helmstow, and the elves will thank you for neither observation."'],
    } },
    { kind: 'sign', x: 3, y: 28, text: 'Brandy Hole. Chalked beneath, in Warden hand: CLOSED. DO NOT ENTER. ASK CAPT. HALE.' },
    { kind: 'well', x: 26, y: 22, text: 'A cistern behind the farm. The water is clean.', heal: true },
    // The Rest of the Survey (#77): Ailith behind the west wood, hiding from the Wardens, until the
    // company tells her where to go.
    { kind: 'event', x: 2, y: 13, id: 'survey_ring', once: true, until: [{ flag: 'q_survey_chapel' }, { flag: 'q_survey_thornhold' }], text: 'A scrap of Lantern grey on a thorn. Beyond it, a fire-ring so small and hidden that its maker feared smoke more than cold.' },
    { kind: 'npc', x: 2, y: 14, name: 'Ailith, adjunct of the survey', lines: [
      'A young woman in torn Lantern grey has her back to an oak and a survey stake held like a spear; her leg is bound in her own hem. "You\'re not Wardens. Wardens don\'t come off the road." The stake comes down an inch. "Adjunct Ailith, of the survey. What\'s left of it."',
      '"It wasn\'t rats. I got out of the cellar when the floor opened and walked into a Warden patrol, and they weren\'t looking for survivors. They wanted our orders. The orders are at our camp over the Deepthorn\'s edge, and the other two went east to reach them first. I went west, and I didn\'t stop to pack."',
      '"The Regent sent us, under his seal: survey the ground under Ashcombe, report to him alone. That was before the Queen died, and before the floor opened. Ask how a man knows where to send a survey before there\'s anything to find. I\'ve asked. I don\'t like the answer, so I\'m hiding from it under a tree."',
    ], flag: 'q_ailith', until: [{ flag: 'q_survey_chapel' }, { flag: 'q_survey_thornhold' }], choice: { ask: '"I can\'t stay under this tree. Where do I go? The Chapel in Helmstow is mine by right, and the Wardens know it. Thornhold is a long walk on this leg, and nobody\'s looking for me there."', answers: [
      { label: 'The Chapel, in Helmstow.', sets: 'q_survey_chapel', says: [
        '"Home, then. Lamps and quiet and my own cell." She tests the leg, and it holds. "If you come asking after me at the Chapel and they say I\'m resting, I\'m resting. Don\'t ask a second time. That\'s not a warning. It\'s advice, from someone who was given it."',
      ] },
      { label: 'Thornhold, over the Scarth.', sets: 'q_survey_thornhold', says: [
        '"Thornhold. Elves and trees and nobody in grey." She takes the stake for a crutch. "Elder Sylvane knows a Lantern\'s word when she hears one. I\'ll tell her about you. She\'ll pretend not to have listened, and then she\'ll have listened. That\'s how the Chapterhouse works."',
      ] },
    ] } },
  ],
  encounters: [
    { id: 'road_rats', x: 16, y: 7, monsters: ['rat', 'rat', 'rat'], aware: 4, respawn: 1440 },
    { id: 'wood_wolves', x: 5, y: 8, monsters: ['wolf', 'wolf'], aware: 5, respawn: 1440 },
    { id: 'wood_boar', x: 7, y: 13, monsters: ['boar'], aware: 3, respawn: 2880 },
    { id: 'road_bandits', x: 13, y: 12, monsters: ['bandit', 'bandit', 'bandit_archer'], aware: 5, respawn: 2880 },
    { id: 'hill_wolves', x: 24, y: 11, monsters: ['wolf', 'wolf', 'wolf'], aware: 5, respawn: 1440 },
    { id: 'marsh_spiders', x: 7, y: 23, monsters: ['spider', 'spider', 'spider', 'spider'], aware: 4, respawn: 1440 },
    { id: 'farm_rats', x: 22, y: 20, monsters: ['rat', 'rat', 'rat', 'rat', 'rat'], aware: 4, respawn: 720 },
    { id: 'beach_crabs', x: 9, y: 28, monsters: ['shore_crab', 'shore_crab', 'shore_crab', 'shore_crab'], aware: 4, respawn: 1440 },
    { id: 'cliff_smugglers', x: 5, y: 26, monsters: ['smuggler', 'smuggler', 'smuggler', 'smuggler_bowman'], aware: 5, respawn: 2880 },
    { id: 'coast_bandits', x: 20, y: 27, monsters: ['bandit', 'bandit', 'bandit', 'bandit_archer', 'bandit_archer'], aware: 5, respawn: 2880 },
  ],
};
