// Caldera as the Cartographers' Guild charts it: a ring of ten areas round the inland sea, two
// islands in it, and the Underdeep beneath. There is one road of levels, numbered I to XIV, but the
// way along it winds: the coast road west out of the Shelf only opens after Thornmark, the east
// road out of Thornmark only once the Tide Stone is back, and three of the steps are crossings of
// the sea. The Shelf and Thornmark are drawn from their own maps, stamped in 1:1 where their areas
// sit (see game/atlas.ts), so the art and the zone overlay agree with what is playable. Everything
// else is planned, and is the design's to change.
//
// The sketch is the world at two cells a character. Legend: . beyond the rim   , grass   T forest
//   t pines   d dead wood   c rift crystal   h hills   e heather   M mountains   A snow peaks
//   V volcano   w fen   _ sand   u dunes   g fused glass   ~ shallows, rivers, lakes   W deep water
//   i ice   a ash   ! lava   * snow   r scree
import type { Atlas } from '../game/atlas.ts';

export const ATLAS: Atlas = {
  width: 192,
  height: 160,
  scale: 2,
  sketch: [
    '................................................................................................',
    '................................................................................................',
    '................................................................................................',
    '...............................M..............M.............M...................................',
    '....................M...MMM.M.M...M.M.M...M.MMM.MMMM.......M....................................',
    '.....................MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM....................................',
    '.....................MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.....................................',
    '.....................MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.....................................',
    '....................MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM..M.....MM..MM.MM....................',
    '.....................MMMM,,,,,,,,,,,,,,MM,,,,,,,,,,,,,,MMMMMMMMMMMMMMMMMMMMM....................',
    '.....................MMMM,,,,,,,,,,,,,,MM,,,,,,,,,,,,,,MMMMMMMMMMMMMMMMMMMMM....................',
    '...................MMMMMM,,,,,,,,,,,,,,MM,,,,,,,,,,,,,,MMMMMMMMMMMMMMMMMMMMM....................',
    '....................MMMMM,,,,,,,,,,,,,,MM,,,,,,,,,,,,,,MMMMMMMMMMMMMMMMMMMMM....................',
    '....................MMMMM,,,,,,,,,,,,,,MM,,,,,,,,,,,,,,MMTTTdddMMMdddhMMMMMM....................',
    '...MM..........MMMM.MMMMM,,,,,,,,,,,,,,MM,,,,,,,,,,,,,,MTTTddddddcddhhMMMMMMM...................',
    '....MM.MM.M.MMM.MMMM.MMMM,,,,,,,,,,,,,,MM,,,,,,,,,,,,,,,TTddcdddddddddhMMMMM....................',
    '....MMMMMMMMMMMMMMMMMMMMM,,,,,,,,,,,,,,MM,,,,,,,,,,,,,,MTddcccddddd,ddhMMMM.M...M.M.M.MM..M.....',
    '.....MMMMMMMMMMMMMMMMMMMM,,,,,,,,,,,,,,MM,,,,,,,,,,,,,,~Tdddcdd,,,,dddhMMMMMMMMMMMMMMMMMMMMM....',
    '.....MMMMMMMMMMMMMMMMMMMM,,,,,,,,,,,,,,MM,,,,,,,,,,,,,,MTTdd,,,,,dddddhMMMMMMMMMMMMMMMMMMMM.....',
    '....MMMMMMMMMMMMMMMMMMMMM,,,,,,,,,,,,,,MM,,,,,,,,,,,,,,M,,,,,dddccdddhhMMMMMMMMMMMMMMMMMMMM.....',
    '....MMMMMMtMMhhhhMMMMMMMM,,,,,,,,,,,,,,MM,,,,,,,,,,,,,,Mdd~dd,dcccccdd,,MMMMMMMMMMMMMMMMMMM.....',
    '.....MMMMttTThhh,,hhhMMMM,,,,,,,,,,,,,,MM,,,,,,,,,,,,,,Mddd~~ddcc!ccd,hhhhhMMMhhhMMMMMMMMMM.....',
    '....MMMMMtTTT,~~,,,hhhMM__WWWWWWWWWWWWWWM,,,,,,,,,,,,,,Mdd,,~dddcccdd,,hhhhhMhhrrhhMMhMMMMM.....',
    '....MMMMMTTT,,,~,,,,,,,,WWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMd,,,,~~,ddd,,,hhhh:hhhhrrrhhhhhMMMM.....',
    '...MMMMMMTT,,,~~,ww,,,__WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWdd,,,,~~,,,,__hhh::hhMMhhhhrrhhMMMM.....',
    '....MMMMMh,,,ww~~www,,__WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW_,,,__,~~_,___~~h:hhMMMhhh!hrhhMMMMM....',
    '....MMMMMhw,www~~~www,_~WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW~__~~~~~~~~~~~~WhhhhhMhhh!!rrhhMMMM.....',
    '....MMMMMwwwww~~w~~ww_~WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW_::hhhhhhh!rhhhMMMM.....',
    '....MMMMMwwww~~ww~~~~~~WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW~_:hhhrrhhhhhhMMMMMM....',
    '.....MMMMwww~~wwwww~w~~WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW~~WWWWWWWWWWW~_hhrrrhhMhhhhMMMMM....',
    '.....MMMMww~~ww~wwww~~~WWWWWWWWWW~~~WWWWWWWWWWWWWWWWWWWWWWW~_r~WWWWWWWWWW~_hhhrhhMMMhhhMMMM.....',
    '.....MMMMww~wwww~~www~~WWWWWWWWW~_rr_~WWWWWWWWWWWWWWWWWWWWWW~~~WWWWWWWWWW~_:hhhhhhMhhh!MMMM.....',
    '.....MMMMwww~www~wwww~WWWWWWWWW~_hhrr_~WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW~~_hh:hhhhhhh!MMMM.....',
    '....MMMMMwwww~ww~~ww~~WWWWWWWWW~_,hhTT_~WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW~_,hhh:hhrrhhhMMMMM....',
    '.....MMMMMwwww~~ww~~~WWWWWWWWW~_,TT,,,_~WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW~_,,hhhhhhrhhhMMMMM....',
    '....MMMMMMMMMMMMMMMMMMMMWWWWWW~_rr,,T,_~WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW~_,,,,eehhhhhhMMMM.....',
    '....MMMMMMMMMMMMMMMMMMMMMWWWWWW~_,,rr_~WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW~_,,eeeeehhheMMMMMM....',
    '...MMMMMMMMMMMMMMMMMMMMMMMWWWWW~~__~__~WWWWWWW~~~~WWWWWWWWWWWWWWWWWWWWWWW~_eeeeeeeeeeeMMMMMM....',
    '...MMMMMMMMMMMMMMMMMMMMMMMMWWWWW~~WW~~WWWWWWW~_hh_~WWWWWWWWWWWWWWWWWWWWWW~_eeehhheeeerMMMMM.....',
    '...M..M.MMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWW~_h,,~WWWWWWWWWWWWWWWWWWWWWW~_~eee~~eeeeeeMMMM.....',
    '........MMMMMuuuuuuuuuuuuW~~WWWWWWWWWWWWWWWWW~_,,_~WWWWWWWWWWWWWWWWWWWWWW~__eeee~eeeeeeMMMMM....',
    '.........MMMMuuuguuuuuuu__~WWWWWWWWWWWWWWWWWWW~__~WWWWWWWWWWWWWWWWWWWWWWW~~_eeeeeeeerreMMMMM....',
    '........MMMMMuuggguuuuuuu_~WWWWWWWWWWWWWWWWWWWW~~WWWWWWWWWWWWWWWWWWWWWWWWW~_eeehhheeeeeMMMM.....',
    '.........MMMMuuugguurruuu_~WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW~_eeeeeeee~~eMMMMM....',
    '.........MMMMuuuuuuurruuu_~WWWWWWWWWWWWWW~WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW~_ee~eeeeee~eMMMMM....',
    '.........MMMMuuuuuuuuuuuuu~WWWWWWWWWWWWWW~~WWWWWWWWWWW~~WWWWWWWWWWWWWWWWWW~_eeeeeeeeeeeMMMMM....',
    '.........MMMMuuuuggguuuuuu_~WWWWWWWWWWWWWWWWWWWWWWWWW~__~WWWWWWWWWWWWWWWWW~__eeehhheeehMMMM.....',
    '........MMMMMuuuugggguuuuu__WWWWWWWWWWWWWWWWWWWWWWWWWW~~WWWWWWWWWWWWWWWWWW~~_eeeeeeeehhMMMM.....',
    '.........MMMMuuuuugguuuuuuuuWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW~_eeee~~eehhMMMM.....',
    '.........MMMMuuruuuuuuuuuuuuWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW~__eeeeeeeeMMMMM.....',
    '.........MMMMuurruuuuuggguuuWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW~_eeeeeeMMMMMMMM....',
    '........MMMMMuuuuuuuuugggguuWWW~~~~~~~~~~WWWMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW~_,,eeeMMMMMMMMM....',
    '.........MMMMuuuuuuuuuuguuuuW~~_______aa~~~WMMWWWWWWWWWWWWWWWWWW~~WWWWWW~_,,,,MMMMMMMMMMMMMM....',
    '........MMMMMuuuuuuuuuuuuuuu~_aaaaa__aaaaa_~MMWWWWWWWWWWWWWWWWWW_~~~~~~~_,,,t,MMMMMMMMMMMMM.....',
    '.........MMMMMMMMMMMMMMMMMMMaaarraaaaaaaaaaaMMMWWWWWWWWWWWWWWWWW,___,,,,,,tt,,,MMMMMMMMMMMMM....',
    '.........MMMMMMMMMMMMMMMMMMMaarrraaaaaVVaaaaMMMMWWWWWWWWWWWWWWWWt,,**i~~i*,,t,,MMMM.MM...M......',
    '.........MMMMMMMMMMMMMMMMMMMaarrraaaaVVVVaaaMMMM__~~WWWWWWWW~~__tt,*i~~~~i*,tt,MMMMM............',
    '.........MMMMMMMMMMMMMMMMMMMaaaaaaaa!VVVVaaaMMMM,,__~~~~~~~~_,,,ttt,*i~~i*,,ttMMMMMM............',
    '........MM.M...M....M..M.MMMaaaaaaa!aaVVaaaaMMMMtt,,,___,,,,,ttttt,,,**,,,i~i,tMMMMM............',
    '.........................MMMaaaa!!!aaaa!aaaaMMMMttAAt,,,,tAAAtt,t,,,i~~i,,*~~*,MMMM.............',
    '........................MMMMaaa!aaaaaaa!aaaaMMMMtAAAAt,,tAAAAAt,,,,i~~~~i,**,,tMMMM.............',
    '........................MMMMaa!!aaaarraa!aaaMMMMAAA*AAt,tAA*AAAt*,,*i~~~i*,,,ttMMMMM............',
    '.........................MMMaaaaaaarrraaa!aaMMMMAA***AA,,AA*AAA,**,,*iii*,,t,ttMMMM.............',
    '.........................MMMaaaaaaaaaaaaaaaaMMMMAAA*AAA,,,,tt,,,A**,,,,,,,ttt*tMMMM.............',
    '........................MMMMMaaaaaaaaaaaaaaMMMMMAAAAAAt,AAAAAAAAAA***,i~~i**tt*MMMMM............',
    '........................MMMMMMMMMMMMMMMMMMMMMMMMAAAAAAA,AAA**AAAAAA**i~~~~i**AMMMMMM............',
    '.........................MMMMMMMMMMMMMMMMMMMMMMMAAA**AA,AA***AAAAAAAA*iiii*AAMMMMMMM............',
    '........................MMMMMMMMMMMMMMMMMMMMMMMMAAAA*AA,,AA*AAAAAAAAAAAAAAAAMMMMMMM.............',
    '........................MMMMMMMMMMMMMMMMMMMMMMMMAAAAAAAA,AAAAAAAMMMMMMMMMMMMMMMMMMM.............',
    '........................M.....MMM.MM..M.M.M..MMMAAAA**AAAAA**AAAMMMMMMMMMMMMMMMMMMMM............',
    '.............................................MMMAAAAAAAAAAAAAAAAMMMMMMMMMMMMMMMMMMMM............',
    '.............................................MMMMMMMMMMMMMMMMMMMMMM..M.......M...M.M............',
    '.............................................MMMMMMMMMMMMMMMMMMMMMM.............................',
    '............................................MMMMMMMMMMMMMMMMMMMMMMM.............................',
    '............................................MMMMMMMMMMMMMMMMMMMMMMM.............................',
    '............................................MMMMMM.M..M.MMMMMMMM................................',
    '.............................................................MM.................................',
    '................................................................................................',
    '................................................................................................',
    '................................................................................................',
  ],
  regions: [
    { id: 'shelf', name: 'The Shelf', order: 1, map: 'shelf', at: [48, 16], stone: 'Harrow Stone', label: [68, 30.5] },
    { id: 'thornmark', name: 'Thornmark', order: 2, map: 'thornmark', at: [80, 16], stone: 'Grove Stone', label: [100, 30], tint: '#94ac62' },
    { id: 'saltreach', name: 'Saltreach', order: 3, at: [16, 38], band: [10, 12], stone: 'Tide Stone', label: [27, 66], note: 'Marsh delta and the smuggler port' },
    { id: 'wrackholm', name: 'Wrackholm', order: 4, at: [58, 58], size: 24, band: [12, 14], label: [70, 80.5], note: 'The smugglers\' isle, where the stolen Tide Stone lies' },
    { id: 'sunderwood', name: 'Sunderwood', order: 5, at: [112, 24], band: [14, 16], label: [126, 50], note: 'The wood the rifts split' },
    { id: 'kilns', name: 'The Kilns', order: 6, at: [144, 40], band: [16, 18], stone: 'Anvil Stone', label: [161, 68], note: 'Dwarf country: mines, forges, lava tubes' },
    { id: 'cairnmoor', name: 'Cairnmoor', order: 7, at: [144, 72], band: [18, 20], label: [163, 99], note: 'Heather moor, cairns and a ring of stones' },
    { id: 'rimewater', name: 'Rimewater', order: 8, at: [128, 104], band: [20, 22], label: [146, 131], note: 'Frozen lakes under the Whitespine' },
    { id: 'whitespine', name: 'The Whitespine', order: 9, at: [96, 112], band: [22, 24], stone: 'Peak Stone', label: [111, 141.5], note: 'The high peaks and the monastery. Mountaineer' },
    { id: 'ashfall', name: 'Ashfall', order: 10, at: [56, 100], band: [24, 26], stone: 'Ember Stone', label: [72, 129], note: 'Volcanic waste, reached only by ship' },
    { id: 'glasswold', name: 'The Glasswold', order: 11, at: [24, 78], band: [26, 28], label: [38, 106], note: 'A desert of fused glass' },
    { id: 'hearth', name: 'Hearth Isle', order: 12, at: [88, 72], size: 16, band: [28, 30], label: [96, 88.5], note: 'The temple over the core' },
  ],
  sites: [
    // I. The Shelf, from its map: Harrow's walls at 14-18,1-3, the Ashcombe farm, the Greywater cliffs.
    { name: 'Harrow', icon: 'city', region: 'shelf', at: [16.5, 2.4], label: 'right' },
    { name: 'Harrow Stone', icon: 'stone', region: 'shelf', at: [21.5, 4], label: 'none', planned: true },
    { name: 'Ashcombe', icon: 'farm', region: 'shelf', at: [26.5, 20.2], label: 'below' },
    { name: 'Greywater', icon: 'cave', region: 'shelf', at: [2.5, 27.4], label: 'below' },
    { name: 'Warden Pass', icon: 'gate', region: 'shelf', at: [31.5, 8.6], label: 'none' },
    // II. Thornmark, from its map.
    { name: 'Thornhold', icon: 'hold', region: 'thornmark', at: [23, 3.2], label: 'below' },
    { name: 'Old Tower', icon: 'tower', region: 'thornmark', at: [4.8, 5], label: 'below' },
    { name: 'Barrow', icon: 'barrow', region: 'thornmark', at: [27.8, 8.4], label: 'below' },
    { name: 'The Grove', icon: 'grove', region: 'thornmark', at: [7.5, 28.6], label: 'right' },
    // III. Saltreach.
    { name: 'Smuggler Port', icon: 'port', region: 'saltreach', at: [27.5, 10.5], label: 'right', planned: true },
    { name: 'Tide Stone', icon: 'stone', region: 'saltreach', at: [11, 12], label: 'below', planned: true },
    { name: 'Drowned Temples', icon: 'sunken', region: 'saltreach', at: [12, 21], label: 'below', planned: true },
    // IV. Wrackholm.
    { name: 'Smugglers\' Cove', icon: 'cave', region: 'wrackholm', at: [9, 9.5], label: 'left', planned: true },
    { name: 'Tide Ship', icon: 'wreck', region: 'wrackholm', at: [15.5, 15.5], label: 'right', planned: true },
    // V. Sunderwood.
    { name: 'Lantern Watch', icon: 'tower', region: 'sunderwood', at: [16, 11], label: 'below', planned: true },
    { name: 'The Sunder', icon: 'rift', region: 'sunderwood', at: [19, 18.5], label: 'below', planned: true },
    // VI. The Kilns.
    { name: 'Dwarf Hold', icon: 'fortress', region: 'kilns', at: [11, 5], label: 'below', planned: true },
    { name: 'Mines', icon: 'mine', region: 'kilns', at: [24, 7], label: 'below', planned: true },
    { name: 'Forges', icon: 'forge', region: 'kilns', at: [19, 16], label: 'below', planned: true },
    { name: 'Anvil Stone', icon: 'stone', region: 'kilns', at: [9, 18], label: 'below', planned: true },
    { name: 'Lava Tubes', icon: 'cave', region: 'kilns', at: [26, 22.5], label: 'below', planned: true },
    // VII. Cairnmoor.
    { name: 'Stone Ring', icon: 'ring', region: 'cairnmoor', at: [18, 11], label: 'below', planned: true },
    { name: 'The Cairns', icon: 'barrow', region: 'cairnmoor', at: [22, 23], label: 'below', planned: true },
    // VIII. Rimewater.
    { name: 'Rime Lodge', icon: 'lodge', region: 'rimewater', at: [22, 5], label: 'below', planned: true },
    { name: 'Ice Caves', icon: 'cave', region: 'rimewater', at: [6, 23], label: 'below', planned: true },
    // IX. The Whitespine.
    { name: 'Monastery', icon: 'monastery', region: 'whitespine', at: [15, 13.5], label: 'right', planned: true },
    { name: 'Peak Stone', icon: 'stone', region: 'whitespine', at: [15, 23], label: 'below', planned: true },
    { name: 'Giants', icon: 'label', region: 'whitespine', at: [25, 20], planned: true },
    // X. Ashfall.
    { name: 'Harbour', icon: 'port', region: 'ashfall', at: [14, 5.5], label: 'right', planned: true },
    { name: 'Ember Stone', icon: 'stone', region: 'ashfall', at: [7, 13], label: 'below', planned: true },
    { name: 'Fire Mountain', icon: 'volcano', region: 'ashfall', at: [22, 15], label: 'none', planned: true },
    // XI. The Glasswold.
    { name: 'Buried Tower', icon: 'obelisk', region: 'glasswold', at: [17, 17], label: 'below', planned: true },
    { name: 'Glass Spires', icon: 'label', region: 'glasswold', at: [22, 25], planned: true },
    // XII. The middle of the world, and the names of the sea and the walls between areas.
    { name: 'The Hearth', icon: 'hearth', at: [96, 79], label: 'none', planned: true },
    { name: 'The Inland Sea', icon: 'label', at: [104, 58] },
    { name: 'The Sheer', icon: 'label', at: [92, 118] },
    { name: 'The Scarp', icon: 'label', at: [30, 72.5] },
  ],
  zones: [
    { id: 'harrow', kind: 'town', at: [64.5, 9.5] },
    { id: 'mill', kind: 'dungeon', at: [80, 50] },
    { id: 'greywater1', kind: 'dungeon', at: [36, 24] },
    { id: 'greywater2', kind: 'dungeon', at: [36, 30] },
    { id: 'thornhold', kind: 'town', at: [104, 9.5] },
    { id: 'grove1', kind: 'dungeon', at: [104, 52] },
    { id: 'grove2', kind: 'dungeon', at: [104, 58] },
    { id: 'salt_port', name: 'Smuggler Port', kind: 'town', planned: true, band: [10, 12], at: [30, 47.5] },
    { id: 'drowned_temples', name: 'Drowned Temples', kind: 'dungeon', planned: true, band: [10, 12], at: [29, 64.5] },
    { id: 'tide_ship', name: 'The Tide Stone', kind: 'dungeon', planned: true, band: [12, 14], at: [70, 86], note: 'a smuggler ship' },
    { id: 'the_sunder', name: 'The Sunder', kind: 'dungeon', planned: true, band: [14, 16], at: [131, 60] },
    { id: 'kilns_hold', name: 'Dwarf Hold', kind: 'town', planned: true, band: [16, 18], at: [157, 34] },
    { id: 'anvil_stone', name: 'The Anvil Stone', kind: 'dungeon', planned: true, band: [16, 18], at: [158, 62.5] },
    { id: 'cairns', name: 'The Cairns', kind: 'dungeon', planned: true, band: [18, 20], at: [174, 104.5] },
    { id: 'ice_caves', name: 'Ice Caves', kind: 'dungeon', planned: true, band: [20, 22], at: [141, 146] },
    { id: 'monastery', name: 'The Monastery', kind: 'dungeon', planned: true, band: [22, 24], at: [111, 150.5] },
    { id: 'ember_stone', name: 'The Ember Stone', kind: 'dungeon', planned: true, band: [24, 26], at: [64, 140] },
    { id: 'buried_tower', name: 'Buried Tower', kind: 'dungeon', planned: true, band: [26, 28], at: [30, 117] },
    { id: 'underdeep', name: 'The Underdeep', kind: 'deep', planned: true, order: 13, band: [30, 31], at: [118, 79] },
    { id: 'core', name: 'The Core', kind: 'deep', planned: true, order: 14, band: [32, 32], at: [118, 86] },
  ],
  links: [
    { from: 'shelf', to: 'saltreach', kind: 'road', opens: 2, a: [49.5, 44.5], b: [44.5, 44.5], note: 'coast road', noteAt: [57, 50.5] },
    { from: 'saltreach', to: 'salt_port', kind: 'enter', a: [43.5, 48.5] },
    { from: 'saltreach', to: 'drowned_temples', kind: 'enter', a: [28, 59] },
    { from: 'saltreach', to: 'wrackholm', kind: 'sea', a: [45, 51], b: [65, 66], note: 'smuggler boat', noteAt: [49, 64] },
    { from: 'wrackholm', to: 'tide_ship', kind: 'enter', a: [73.5, 73.5] },
    { from: 'thornmark', to: 'sunderwood', kind: 'road', opens: 4, a: [108.5, 30.5], b: [115.5, 30.5], note: 'when the rifts recede', noteAt: [112, 36.5] },
    { from: 'sunderwood', to: 'the_sunder', kind: 'enter', a: [131, 42.5] },
    { from: 'sunderwood', to: 'kilns', kind: 'road', a: [141, 48.5], b: [147, 48.5] },
    { from: 'kilns', to: 'kilns_hold', kind: 'enter', a: [155, 45] },
    { from: 'kilns', to: 'anvil_stone', kind: 'enter', a: [153, 58] },
    { from: 'kilns', to: 'cairnmoor', kind: 'road', a: [160, 68.5], b: [160, 75.5] },
    { from: 'cairnmoor', to: 'cairns', kind: 'enter', a: [166, 95] },
    { from: 'cairnmoor', to: 'rimewater', kind: 'road', a: [150, 100.5], b: [150, 107.5] },
    { from: 'rimewater', to: 'ice_caves', kind: 'enter', a: [134, 127] },
    { from: 'rimewater', to: 'whitespine', kind: 'road', a: [131.5, 120.5], b: [124.5, 120.5], note: 'Mountaineer', noteAt: [128, 126] },
    { from: 'whitespine', to: 'monastery', kind: 'enter', a: [111, 125.5] },
    { from: 'saltreach', to: 'ashfall', kind: 'sea', opens: 9, a: [44, 53], b: [69, 105.5], note: 'Compact ship', noteAt: [38, 75] },
    { from: 'ashfall', to: 'ember_stone', kind: 'enter', a: [63, 113] },
    { from: 'ashfall', to: 'glasswold', kind: 'road', a: [59.5, 104.5], b: [52.5, 104.5] },
    { from: 'glasswold', to: 'buried_tower', kind: 'enter', a: [41, 95] },
    { from: 'ashfall', to: 'hearth', kind: 'sea', opens: 11, a: [72, 103.5], b: [92, 85], note: 'the last crossing', noteAt: [92, 99] },
    { from: 'hearth', to: 'underdeep', kind: 'deep', a: [98, 79] },
    { from: 'underdeep', to: 'core', kind: 'deep' },
  ],
  trails: [
    [[48, 44.5], [45, 46], [43.5, 48.5], [38, 52], [33, 56], [28, 59]],
    [[111, 30.5], [118, 31], [124, 35], [131, 42.5], [137, 46], [144, 48.5]],
    [[144, 48.5], [150, 48], [155, 45], [158, 52], [153, 58], [157, 64], [160, 72]],
    [[160, 72], [159, 80], [154, 84], [162, 83], [166, 95], [158, 97], [150, 104]],
    [[150, 104], [146, 110], [150, 109], [140, 114], [134, 118], [128, 120.5]],
    [[128, 120.5], [120, 122], [115, 125], [111, 125.5]],
    [[70, 105.5], [66, 109], [63, 113], [60, 108], [56, 104.5]],
    [[56, 104.5], [48, 101], [41, 95]],
    [[65, 66], [67, 68], [73.5, 73.5]],
  ],
};
