// Thornmark: old forest east of the Shelf, reached through the mountain pass once Vask opens it.
// Thornhold in the north-east, a ruined Warden watchtower in the north-west, a barrow on the
// eastern hills, a river with one bridge, and the Grove in the deep woods to the south-west.
// Difficulty band 5-10.
import type { MapDef } from '../../game/map.ts';
import { EAST, NORTH, SOUTH, WEST } from '../../game/types.ts';

export const THORNMARK: MapDef = {
  id: 'thornmark',
  name: 'Thornmark',
  kind: 'outdoor',
  band: [5, 10],
  region: 'thornmark',
  start: { x: 1, y: 9, facing: EAST },
  palette: { floor: '#3f8a34', banner: '#2a6a3a' },
  rows: [
    'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM',
    'M,,T,,,,,,,,,,,,,,,,,,,,,,,,,,,M',
    'M,,,,,TT,,,,,,,,,,,,,BBBBB,,,T,M',
    'M,T,,,TTT,,,,,,,,,,,,BBBBB,,,,,M',
    'M,,,BB,T,,,,,,,,,,,,,BB=BB,,T,,M',
    'M,,,BB,,,,,,,,,,,,,,,,,=,,,,,,,M',
    'M,r,,,,,,,,,,,,,,,,,,,,=,,,,,,,M',
    'M,rr,,,,,,,,,,,,,,,,,,,=,,,rr,,M',
    'M,,r,,,,,,,,,,==========,,,rrr,M',
    '==============,,,,,,,,,,,,,,r,,M',
    'M,,,,,,,,,,,,=,,,,,,,,,,,,,,,,,M',
    'M,TT,,,,,,,,,=,,,,,,,,,,,,,,,,,M',
    'M,TTT,,,,,,,,=,,,,,T,,,,,,,,,,,M',
    'M,,TT,,,,,,,,=,,,,TTT,,,,,,,,,,M',
    'M,,,,,,,,,,,,=,,,,,T,,,,,,,,,,,M',
    'M,,,,,,,,,,,,=,,,,,,,,,,,,,,,,,M',
    'M,,,,,,,,,,,,=,,,,,,,,,,,,,,,,,M',
    'M,,,,,,,,,,,,=,,,,,,,,,,,,,,,,,M',
    'M~~~~~~~~~~~~=~~~~~~~~~~~~~~~~~M',
    'M,,,,,,,,,,,,=,,,,,,,,,,,,,,,,,M',
    'M,,,,,,,,,,,,=,,,,,,,,,,,,,,,~~M',
    'M,,,,,,,,,,,,=,,,,,,,,,,,,,,~~~M',
    'M,,T,,,,,,,,,=,,,,,,,,,,,,,~~~~M',
    'M,TTT,,,,,,,,=,,,,,,,,,,,,,,~~~M',
    'M,TTTT,,======,,,,,,,,,,,,,,,,,M',
    'M,TT,,,=,,,,,,,,,,,,,,,,,,,,,,,M',
    'M,T,,,,=,,,,,,,,,,,rr,,,,,,,,,,M',
    'M,,,,,,=,,,,,,,,,,,r,,,,,,,,,,,M',
    'M,,TTT,=,TTT,,,,,,,,,,,,,,,,,,,M',
    'M,TTTTT=TTTTT,,,,,,,,,,,,,,,,,,M',
    'M,TTTTTTTTTTT,,,,,,,,,,,,,,,,,,M',
    'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM',
  ],
  exits: [
    { x: 0, y: 9, to: 'shelf', tx: 30, ty: 9, tf: WEST, label: 'Back through the pass to the Shelf.' },
    { x: 23, y: 4, to: 'thornhold', tx: 7, ty: 14, tf: NORTH, label: 'You pass under the oak gate of Thornhold.' },
    { x: 7, y: 29, to: 'grove1', tx: 1, ty: 1, tf: SOUTH, label: 'Steps cut into the roots lead down beneath the Grove.' },
  ],
  features: [
    { kind: 'event', x: 1, y: 9, id: 'thornmark_in', once: true, text: 'Thornmark. The trees here are older than Harrow, and the Warden road under them has not been swept in weeks.' },
    { kind: 'sign', x: 13, y: 9, text: 'North-east: Thornhold. South, over the bridge: the Grove. Wardens turn back here.' },
    { kind: 'sign', x: 13, y: 19, text: 'The Grove. By order of the Elder, none but Lanterns past this bridge.' },
    { kind: 'sign', x: 23, y: 5, text: 'Thornhold. Elves and honest folk welcome. Leave the trees standing.' },
    { kind: 'event', x: 5, y: 6, id: 'tower', once: true, text: 'The old Warden watchtower, roofless. Something large has made a den in its base; the bones outside are not all animal.' },
    { kind: 'chest', x: 6, y: 5, id: 'tm_tower', gold: 180, items: ['warhammer', 'elixir', 'lantern_oil'] },
    { kind: 'event', x: 26, y: 8, id: 'barrow', once: true, text: 'A barrow, its door-stone rolled aside from within. The grass around it is dead in a ring.' },
    { kind: 'chest', x: 30, y: 9, id: 'tm_barrow', gold: 260, items: ['rune_dagger', 'potion_sp_great'] },
    { kind: 'event', x: 13, y: 24, id: 'grove_road', once: true, text: 'The road narrows and the oaks lean in over it. Every trunk on this stretch carries a chisel mark at shoulder height.' },
    { kind: 'event', x: 7, y: 25, id: 'grove_edge', once: true, text: 'The trees close in. Ahead the road ends in a hollow ringed with oaks: the Grove. The air hums, faintly, the way the cellar under Ashcombe did.' },
    { kind: 'event', x: 20, y: 23, id: 'lake', once: true, text: 'A still lake. On the far shore, half-sunk, a Lantern survey marker with its glass gone dark.' },
  ],
  encounters: [
    { id: 'tm_wolves1', x: 5, y: 9, monsters: ['dire_wolf', 'dire_wolf', 'dire_wolf', 'dire_wolf'], aware: 5, respawn: 1440 },
    { id: 'tm_ogre', x: 5, y: 7, monsters: ['ogre', 'brigand', 'brigand'], aware: 3, roams: false },
    { id: 'tm_brigands1', x: 23, y: 7, monsters: ['brigand', 'brigand', 'brigand', 'brigand', 'brigand_archer', 'brigand_archer'], aware: 5, respawn: 2880 },
    { id: 'tm_barrow', x: 26, y: 8, monsters: ['bone_knight', 'bone_knight', 'bone_knight'], aware: 3, roams: false },
    { id: 'tm_wraiths', x: 30, y: 7, monsters: ['wraith', 'wraith'], aware: 3, roams: false },
    { id: 'tm_spiders1', x: 17, y: 13, monsters: ['thorn_spider', 'thorn_spider', 'thorn_spider', 'thorn_spider', 'thorn_spider'], aware: 5, respawn: 1440 },
    { id: 'tm_brigands2', x: 13, y: 15, monsters: ['brigand', 'brigand', 'brigand', 'brigand_archer', 'brigand_archer'], aware: 5, respawn: 2880 },
    { id: 'tm_wolves2', x: 20, y: 16, monsters: ['dire_wolf', 'dire_wolf', 'dire_wolf', 'dire_wolf', 'dire_wolf'], aware: 5, respawn: 1440 },
    { id: 'tm_wolves3', x: 26, y: 14, monsters: ['dire_wolf', 'dire_wolf', 'dire_wolf', 'boar', 'boar'], aware: 5, respawn: 1440 },
    { id: 'tm_hounds', x: 13, y: 21, monsters: ['rift_hound', 'rift_hound', 'rift_hound'], aware: 6, respawn: 2880 },
    { id: 'tm_spiders2', x: 10, y: 22, monsters: ['thorn_spider', 'thorn_spider', 'thorn_spider', 'thorn_spider', 'thorn_spider', 'thorn_spider'], aware: 5, respawn: 1440 },
    { id: 'tm_zealots', x: 7, y: 26, monsters: ['zealot', 'zealot', 'zealot', 'ashen_adept'], aware: 5, respawn: 2880 },
    { id: 'tm_elders', x: 12, y: 27, monsters: ['riftling_elder', 'riftling_elder', 'riftling', 'riftling', 'riftling'], aware: 5, respawn: 2880 },
    { id: 'tm_lake', x: 24, y: 21, monsters: ['thorn_spider', 'thorn_spider', 'thorn_spider', 'rift_hound', 'rift_hound'], aware: 5, respawn: 1440 },
  ],
};
