// The Deepthorn, box I4: Henlys. Core, band 8-10: the oldest elf-hold, its halls grown into oaks
// and its gate shut against its own wood, where the treaty sealed with the chisel's mark is kept; the
// old groves round it, where the rootwalkers stand in rings, and behind their holly the hold's first
// grove; the long glade down the box's east side, the road on to the head; the Wyke's shore on the
// west. Cut from the atlas by tools/scaffold.ts; docs/areas/thornmark.md §4.4 is its brief.
import type { MapDef } from '../../../../game/map.ts';
import { SOUTH } from '../../../../game/types.ts';

export const DEEPTHORN_I4: MapDef = {
  id: 'deepthorn_i4',
  name: 'The Deepthorn',
  kind: 'outdoor',
  density: 'core',
  band: [8, 10],
  region: 'thornmark',
  start: { x: 12, y: 0, facing: SOUTH },
  rows: [
    'TTTTTTTTTTTT:TTTTTTTTTTTTTTTTTTT',
    'TTTTTTTTTTTT:TTTTTTTTTTTTTTTTTTT',
    'TTTTTTTTTTTT:TTTTTTTTTTTTTTTTTTT',
    'TTTTTTTTTTTT:TTTTTTTTTTT,TTTTTTT',
    'TTTTTTTTTTTT:TTTTTTTTTTT,,,,,TTT',
    'TTTTTBBBBBBB,BBBBTTTTTTT,,,,,TTT',
    'TTTTTBBBBBBB,BBBBTTTTTTTT,,,,,,T',
    'TTTTTBBBB,,,,,,BBTTTTTTTTT,,,,,T',
    'TTTTTBBBB,,,,,,BBTTTTTTTTT,,,,,,',
    'TTTTTBB,,,,,,,,BBTTTTTTTTT,,,,,,',
    'TTTTTBB,,,,,,,,,,::::::::::,,,,,',
    'TTTTTBB,,,,,,,,BBTTTTTTTTT,,,,,,',
    'TTTTTBB,,,,,,,,BBTTTTTTTTT,,,,,,',
    '~TTTTBB,,,,,,,,BBTTTTTTTTT,,,,,,',
    '~TTTTBBBBB,BBBBBBTTTTTTTTTTT,,,,',
    '~~~TTBBBBB,BBBBBBTTTTTTTTTTT,,,,',
    'W~~~~TTTTT:TTTTTTTTTTTTTTTTT,,,,',
    'WWW~~TTTTT:TTTTTTTTTTTTTTTTT:,,,',
    'WWWW~~~,,,,,,,,,,,,,,TTTTTTT:TTT',
    'WWWW~~,,,,,,,,,,,,,,,TTTTTTT:TTT',
    'WWWW~~TTT,,,TTT,,,,,,T,,,,TT:TTT',
    'WWWW~~TTT,,,TTT,,,,,,T,,,,TT:TTT',
    'WWWW~~TTT,,,TTT,,TTT,S,,,,TT:TTT',
    'WWWW~~,,,,,,,,,,,TTT,T,,,,TT:TTT',
    'WWWW~~TTT,,,TTT,,TTT,T,,,,TT:TTT',
    'WWWWW~~TT,,,TTT,,,,,,TTTTTTT:TTT',
    'WWWWWW~~T,,,TTT,,,,,,TTTTTTT:TTT',
    'WWWWWWW~~,,,,,,,,,,,,TTTTTTT:TTT',
    'WWWWWWWW~~~TTTTTTTTT:::::::::TTT',
    'WWWWWWWWW~~~~~TTTTTTTTTTTTTTTTTT',
    'WWWWWWWWWWW~~~~~~TTTTTTTTTTTTTTT',
    'WWWWWWWWWWWWWW~~~~TTTTTTTTTTTTTT',
  ],
  features: [
    { kind: 'event', x: 12, y: 3, id: 'i4_gate', once: true, text: 'Henlys. Halls grown into oaks wider than houses, and brambles standing in the shut gate like a guard.' },
    { kind: 'event', x: 12, y: 7, id: 'i4_inside', once: true, text: 'Inside, the hold is quiet the way a held breath is quiet. Elves watch you from the galleries, and nobody comes down.' },
    { kind: 'camp', x: 11, y: 8, name: 'The gate-yard hearth', text: 'A hearth in the gate-yard, kept lit for travellers by a custom older than the gate.' },
    { kind: 'well', x: 13, y: 12, heal: true, text: 'The hold\'s spring, cold from under the oaks.' },
    { kind: 'event', x: 9, y: 8, id: 'i4_treaty', once: true, text: 'The hall, a hollow oak. Under horn at its end, a treaty with two seals: the Crown\'s, and the hold\'s oldest mark.' },
    { kind: 'sign', x: 26, y: 10, text: 'A sign reads: "West: the hold. South, down the glade: the head. Past the glade the hold keeps no peace, and asks none."' },
    { kind: 'statue', x: 24, y: 3, id: 'i4_statue', name: 'The first elder', text: 'A statue of the hold\'s first elder, its face gone to lichen, one hand raised as if towards a gate.',
      riddle: 'I was here before the hold, and I will be here when its gate is grass. Thornhold\'s gate says what to leave me.', answer: 'standing',
      gift: { items: ['brigandine+3'] }, done: 'The stone hand is down, and what it held is yours. The lichen is taking the face again.' },
    { kind: 'event', x: 10, y: 19, id: 'i4_groves', once: true, text: 'The old groves: oaks in rings, and rootwalkers among them like stumps. Every one faces the same way.' },
    { kind: 'event', x: 20, y: 22, id: 'i4_holly', once: true, text: 'Every rootwalker in the groves is turned the same way: towards a wall of holly on the east side.' },
    { kind: 'event', x: 23, y: 22, id: 'i4_first_grove', once: true, text: 'One oak behind the holly, older than the rings, and at its roots, in rows, the dead hunters\' bows, unstrung.' },
    { kind: 'chest', x: 24, y: 21, id: 'i4_bows', gold: 90, items: ['elfbow+2'] },
  ],
  secrets: [{ x: 21, y: 22, hint: 'i4_holly' }],
  encounters: [
    { id: 'i4_gate_brambles', x: 12, y: 5, monsters: ['bramble', 'bramble', 'bramble'], aware: 1, roams: false, respawn: 2880 },
    { id: 'i4_east_brambles', x: 21, y: 10, monsters: ['bramble', 'bramble', 'bramble'], aware: 1, roams: false, respawn: 2880 },
    { id: 'i4_south_brambles', x: 10, y: 17, monsters: ['bramble', 'bramble', 'bramble'], aware: 1, roams: false, respawn: 2880 },
    { id: 'i4_oak', x: 17, y: 27, monsters: ['heartwood', 'bramble', 'bramble', 'bramble'], aware: 2, roams: false, respawn: 2880 },
    { id: 'i4_walkers_west', x: 6, y: 23, monsters: ['rootwalker', 'rootwalker', 'rootwalker'], aware: 3, respawn: 2880 },
    { id: 'i4_walkers_east', x: 16, y: 23, monsters: ['rootwalker', 'rootwalker', 'rootwalker'], aware: 3, respawn: 2880 },
    { id: 'i4_night', x: 28, y: 23, when: { hours: 'night' }, monsters: ['great_owl', 'great_owl', 'bramble', 'bramble'], aware: 3, respawn: 1440 },
    { id: 'i4_wolves', x: 29, y: 8, monsters: ['dire_wolf', 'dire_wolf', 'dire_wolf', 'dire_wolf', 'dire_wolf', 'dire_wolf', 'dire_wolf', 'dire_wolf'], aware: 5, respawn: 1440 },
    { id: 'i4_spiders', x: 9, y: 27, monsters: ['thorn_spider', 'thorn_spider', 'thorn_spider', 'thorn_spider', 'thorn_spider', 'thorn_spider'], aware: 4, respawn: 1440 },
  ],
};
