// Wrackholm, box F6: the east rocks, the moor's rocky end and the anchorage under the cliffs.
// Core, band 13-14. DRAFT.
import type { MapDef } from '../../../../game/map.ts';
import { EAST } from '../../../../game/types.ts';

const BURNT = { seen: 'wrackholm_f6:f6_watch' };

export const WRACKHOLM_F6: MapDef = {
  id: 'wrackholm_f6',
  name: 'Wrackholm',
  kind: 'outdoor',
  density: 'core',
  band: [13, 14],
  region: 'wrackholm',
  start: { x: 0, y: 12, facing: EAST },
  rows: [
    ',,,,,,,,,,^,,,,,,__~~~~WWWWWWWWW',
    ',,,,,,,,,,,,,,,,,,,___~~WWWWWWWW',
    ',,,,,,,,,,,,,,,,,,,,,,_~~~WWWWWW',
    ',,,,,,,,,,,,,,,,,,,,,,,_~~~WWWWW',
    ',,,,,,,,,,,,,,,,,,,,,,,,__~~WWWW',
    ',,hhhhhh,,,,,,,,,,,,,,,,,,_~~WWW',
    'hhhhhhhhhh,,rrrr,,,,,,,,,,,_~~WW',
    'hhhhhhhhhhh,rrrrrr,,,,,,,,,_~~WW',
    'hhhhhhhhhhhhrrrrrrr,,,,,,,,,_~~W',
    'hhhhhhhhhhhhrrrrrrrrr,,,,,,,_~~W',
    'hhhhhhhhhhhhrrrrrrrrr,,,,,,,,_~~',
    'hhhhhhhhhhhhrrrrrrrrrr,,,,,,,_~~',
    'hhhhhhhhhhhhhrrrrrrrrr,,,,B,,_~~',
    'hhhhhhhhhhhhhrrrrrrrrr,,,,,,rr~~',
    'hhhhhhhhhhhhhrrrr"rrrr,,,,,,S"r~',
    'hhhhhhhhhhhhhrrr"""rrr,,,,,,rr~~',
    'hhhhhhhhhhhhhhrrr"rrrrr,,,,,,^~~',
    'hhhhhhhhhhhhhhhrr"rrrrr,,,,,,,~~',
    'hhhhhhhhhhhhhhhrr"rrrr,,,,,,,,~~',
    'hhhhhhhhhhhhhh,,,,,,,,,,,,,,,~~W',
    'hhhhhhhhhhhhh,,,,,,,,,,,,,,,,~~W',
    'hhhhhhhhhhhh,,,,,,,,,,,,,,,,_~~W',
    'hhhhhhhhhhh,,,,,,,,,,,,,,,,_~~WW',
    'hhhhhhhhhhhh^^^,,,,,,,,,,,,_~~WW',
    'hhhhhhhhhhh^^^^^^,,,,,,,,,_~~WWW',
    'hhhhhhhhh,,rr^^rr,,,,,,,,_~~WWWW',
    'hhhhhhhhh,,rrr^rr,,,,,,,_~~WWWWW',
    'hhhhhh,,,,,rr^^rr,,,,,,,_~~WWWWW',
    'hhhhh,,,,,,,rr^rr,,,,,__~~WWWWWW',
    ',h,hh,,,,,,,r_^_r,,,,_~~~WWWWWWW',
    '_,,,,,,,,,,,r___r,,,_~~~WWWWWWWW',
    '~_,,,,,,,,,rr___r,,_~~WWWWWWWWWW',
  ],
  features: [
    { kind: 'event', x: 1, y: 12, id: 'f6_moor', once: true, text: 'TODO moor' },
    { kind: 'npc', x: 26, y: 13, name: 'the hermit', lines: ['TODO hermit 1', 'TODO hermit 2'] },
    { kind: 'event', x: 25, y: 12, id: 'f6_tally', once: true, text: 'TODO tally' },
    { kind: 'event', x: 27, y: 14, id: 'f6_cairn', once: true, text: 'TODO cairn' },
    { kind: 'chest', x: 29, y: 14, id: 'f6_grave', gold: 150, items: ['founders_seal'] },
    { kind: 'event', x: 29, y: 14, id: 'f6_grave_seen', once: true, text: 'TODO grave' },
    { kind: 'event', x: 14, y: 24, id: 'f6_clifftop', once: true, when: { hours: 'day' }, text: 'TODO ship by day' },
    { kind: 'event', x: 14, y: 30, id: 'f6_boats', once: true, when: { hours: 'night' }, text: 'TODO boats' },
    { kind: 'event', x: 14, y: 29, id: 'f6_shingle', once: true, when: { hours: 'day' }, text: 'TODO shingle' },
    { kind: 'den', x: 17, y: 14, id: 'f6_watch', name: 'The watch', text: 'TODO watch',
      breeds: ['wrack_smuggler', 'wrack_bowman'], keepers: 'f6_keepers', brood: ['f6_crew'],
      ask: 'TODO ask', burn: 'Burn it.', leave: 'Leave it.', burnt: 'TODO burnt', ruin: 'TODO ruin', gold: 80, items: [] },
    { kind: 'event', x: 25, y: 21, id: 'f6_stores', once: true, text: 'TODO stores' },
    { kind: 'event', x: 20, y: 28, id: 'f6_pools', once: true, text: 'TODO pools' },
    { kind: 'camp', x: 7, y: 28, name: 'TODO hollow', text: 'TODO camp' },
    { kind: 'shrine', x: 23, y: 4, id: 'f6_shrine', text: 'TODO shrine', stat: 'personality', done: 'TODO done' },
    { kind: 'event', x: 6, y: 4, id: 'f6_north', once: true, text: 'TODO north' },
    { kind: 'event', x: 6, y: 18, id: 'f6_heather', once: true, text: 'TODO heather' },
    { kind: 'event', x: 22, y: 10, id: 'f6_rockfoot', once: true, text: 'TODO rocks east' },
    { kind: 'event', x: 17, y: 20, id: 'f6_cleft', once: true, text: 'TODO cleft' },
  ],
  secrets: [{ x: 28, y: 14, hint: 'f6_tally' }],
  encounters: [
    { id: 'f6_gulls', x: 14, y: 4, monsters: new Array(8).fill('wrack_gull'), aware: 4, respawn: 1440 },
    { id: 'f6_crew', x: 9, y: 20, monsters: ['wrack_smuggler', 'wrack_smuggler', 'wrack_bowman', 'wrack_bowman'], back: 2, aware: 3, respawn: 2880, until: BURNT },
    { id: 'f6_keepers', x: 17, y: 15, monsters: ['ashen_overseer', 'ashen_overseer', 'ashen_gleaner', 'ashen_gleaner'], aware: 2, roams: false },
    { id: 'f6_rats', x: 24, y: 22, monsters: new Array(8).fill('bilge_rat'), aware: 2, respawn: 1440 },
    { id: 'f6_devilfish', x: 20, y: 29, when: { hours: 'night' }, monsters: ['devilfish', 'devilfish', 'devilfish', 'devilfish'], aware: 2, roams: false, respawn: 2880 },
  ],
};
